# Generated by Django 4.2.27 on 2025-12-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name/Location')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('vendor', models.CharField(default='MikroTik', max_length=50, verbose_name='Vendor')),
                ('api_port', models.IntegerField(default=8728, verbose_name='API Port')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Router',
                'verbose_name_plural': 'Routers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Profile Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Router Profile',
                'verbose_name_plural': 'Router Profiles',
                'ordering': ['name'],
            },
        ),
    ]
