# Generated by Django 4.2.27 on 2025-12-16 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Package Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monthly Price (KES)')),
                ('duration_days', models.IntegerField(default=30, verbose_name='Duration in Days')),
                ('max_download_speed', models.IntegerField(verbose_name='Max Download Speed (Mbps)')),
                ('max_upload_speed', models.IntegerField(verbose_name='Max Upload Speed (Mbps)')),
                ('data_cap_mb', models.BigIntegerField(default=0, verbose_name='Data Cap (MB)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mikrotik_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routers.routerprofile', verbose_name='MikroTik User Profile')),
            ],
            options={
                'verbose_name': 'WiFi Package',
                'verbose_name_plural': 'WiFi Packages',
                'ordering': ['price'],
            },
        ),
    ]
