# Generated by Django 4.2.27 on 2025-12-16 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('INTERNET', 'No Internet / Slow Speed'), ('BILLING', 'Billing Issue'), ('RELOCATION', 'Relocation Request'), ('OTHER', 'Other')], default='INTERNET', max_length=20)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_response', models.TextField(blank=True, help_text='Reply visible to the user', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('is_public', models.BooleanField(default=True, help_text='Check to make this update visible to the customer on the portal.')),
                ('action', models.CharField(choices=[('COMMENT', 'Comment'), ('STATUS_CHANGE', 'Status Change'), ('ASSIGNMENT', 'Assignment')], default='COMMENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='support.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
